### ISSUE TITLE
Calling /api/<model>/<id>/<attribute> where <attribute> is not a relation bombs with an unhelpful AttributeError

### ISSUE THREAD

**Issue by jcmcken** [jfinkels/flask-restless#213]
Curl command that I run:

```text
curl http://localhost:5000/api/v1/data/1/id
```

...where ``data`` is my ``collection_name``, ``/api/v1`` is my ``url_prefix``, and ``id`` is just the name of the primary key column.

I get this exception:

```text
AttributeError: 'ColumnProperty' object has no attribute 'uselist'
```

I don't think this is a proper usage of the API,  but the error is not helpful. If it's not a valid endpoint, API should raise a 400-level http code, not a 500.

A different AttributeError is raised (with 500 HTTP code) if you call with an attribute that doesn't even exist for the given model, which also seems to be a bug.

Full traceback for the first issue:

```text
Traceback (most recent call last):
  File "/data/sandbox/apps/myapp/venv/lib/python2.6/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/data/sandbox/apps/myapp/venv/lib/python2.6/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/data/sandbox/apps/myapp/venv/lib/python2.6/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/data/sandbox/apps/myapp/venv/lib/python2.6/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/data/sandbox/apps/myapp/venv/lib/python2.6/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/data/sandbox/apps/myapp/venv/lib/python2.6/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/data/sandbox/apps/myapp/venv/lib/python2.6/site-packages/flask_restless/views.py", line 112, in decorator
    return func(*args, **kw)
  File "/data/sandbox/apps/myapp/venv/lib/python2.6/site-packages/flask/views.py", line 83, in view
    return self.dispatch_request(*args, **kwargs)
  File "/data/sandbox/apps/myapp/venv/lib/python2.6/site-packages/flask/views.py", line 150, in dispatch_request
    return meth(*args, **kwargs)
  File "/data/sandbox/apps/myapp/venv/lib/python2.6/site-packages/flask_restless/views.py", line 935, in get
    if is_like_list(instance, relationname):
  File "/data/sandbox/apps/myapp/venv/lib/python2.6/site-packages/flask_restless/helpers.py", line 228, in is_like_list
    return instance._sa_class_manager[relation].property.uselist
AttributeError: 'ColumnProperty' object has no attribute 'uselist'
```

My requirements file:

```text
Flask==0.9
Flask-Restless==0.11.0
Flask-SQLAlchemy==0.16
FormEncode==1.2.6
Jinja2==2.7
MarkupSafe==0.18
SQLAlchemy==0.8.1
Werkzeug==0.8.3
python-dateutil==2.1
six==1.3.0
wsgiref==0.1.2
```

**Comment by jfinkels** [comment]
This is fixed on the master branch. You now get an error response with the message `No such relation: "id"`
