### ISSUE TITLE
Unable to make search query using related model.

### ISSUE THREAD

**Issue by TimotheeJeannin** [jfinkels/flask-restless#358]
From the [**query format** section of the documentation](https://flask-restless.readthedocs.org/en/latest/searchformat.html#query-format)

    <fieldname> may alternately specify a field on a related model, 
    if it is a string of the form <relationname>__<fieldname>

Let's say I have several computers owner by several persons. 
Let's say all those persons are grouped into companies. 
So I would build my models like this:

```python 
class Computer(Base):
    id = Column(Integer, primary_key=True)
    owner_id = Column(Integer, ForeignKey('person.id'))
    owner = relationship('Person')

class Person(Base):
    id = Column(Integer, primary_key=True)
    company_id = Column(Integer, ForeignKey('company.id'))
    name = Column(Unicode, unique=True)
    computers = relationship('Computer')

class Company(Base):
    id = Column(Integer, primary_key=True)
    name = Column(Unicode, unique=True)
    persons = relationship('Person')
```
I want to retrieve the list of computers for a particular company. 
According to the documentation, I would do (with 678 the id of the particular company):

    /api/computer?q={"filters":[{"name":"owner__company_id","op":"==","val":"678"}]}

But when I run this search query, my application is crashing. 

Here is a failing test case for the `TestQueryCreation` class

```python
    def test_query_related_field_equality(self):
        """Test for making a query with respect to a related field."""
        # add a computer to person 1
        computer1 = self.Computer(name=u'1', vendor=u'Dell')
        computer2 = self.Computer(name=u'2', vendor=u'Dell')
        computer3 = self.Computer(name=u'3', vendor=u'Dell')
        p1 = self.session.query(self.Person).filter_by(id=1).first()
        p2 = self.session.query(self.Person).filter_by(id=2).first()
        p1.computers.append(computer1)
        p1.computers.append(computer2)
        p2.computers.append(computer3)
        self.session.commit()

        d = {'filters': [{'name': 'owner__id', 'val': u'1', 'op': 'eq'}]}
        query = create_query(self.session, self.Computer, d)
        assert query.count() == 2
```

Here is what the stack trace looks like:

    Traceback (most recent call last):
      File "/home/tim/Workspace/flask-restless/env/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
        self.test(*self.arg)
      File "/home/tim/Workspace/flask-restless/tests/test_search.py", line 106, in test_query_related_field_equality
        query = create_query(self.session, self.Computer, d)
      File "/home/tim/Workspace/flask-restless/flask_restless/search.py", line 454, in create_query
        return QueryBuilder.create_query(session, model, searchparams)
      File "/home/tim/Workspace/flask-restless/flask_restless/search.py", line 412, in create_query
        filters = QueryBuilder._create_filters(model, search_params)
      File "/home/tim/Workspace/flask-restless/flask_restless/search.py", line 381, in _create_filters
        param = create_op(model, fname, filt.operator, val, relation)
      File "/home/tim/Workspace/flask-restless/flask_restless/search.py", line 349, in _create_operation
        return opfunc(field, argument)
      File "/home/tim/Workspace/flask-restless/flask_restless/search.py", line 80, in <lambda>
        'eq': lambda f, a: f == a,
      File "/home/tim/Workspace/flask-restless/env/local/lib/python2.7/site-packages/sqlalchemy/sql/operators.py", line 298, in __eq__
        return self.operate(eq, other)
      File "/home/tim/Workspace/flask-restless/env/local/lib/python2.7/site-packages/sqlalchemy/orm/attributes.py", line 176, in operate
        return op(self.comparator, *other, **kwargs)
      File "/home/tim/Workspace/flask-restless/env/local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1002, in __eq__
        other, adapt_source=self.adapter))
      File "/home/tim/Workspace/flask-restless/env/local/lib/python2.7/site-packages/sqlalchemy/orm/relationships.py", line 1338, in _optimized_compare
        value = attributes.instance_state(value)
    AttributeError: 'unicode' object has no attribute '_sa_instance_state'

Should I try to write a patch for `flask-restless` ? 
Is there another way to achieve that ?  

Thank you for this awesome project! :)

**Comment by jfinkels** [comment]
We no longer support the double underscore, but the main issue (providing a bad name to a filter object causes a crash) has been fixed. See d79b45f94b4ad38b3378443b24026c5e7fb949ca.
