### ISSUE TITLE
DELETE on child item dont work

### ISSUE THREAD

**Issue by cebor** [jfinkels/flask-restless#361]
Hi i tried this command via curl: [DELETE](http://flask-restless.readthedocs.org/en/latest/requestformat.html#delete--api-person-(int-id)-computers-(int-id))

CMD:
```
curl -i localhost:5000/customer/1/projects/2 -XDELETE
```

Got following error:
```
Traceback (most recent call last):
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask_restless/views.py", line 139, in decorator
    return func(*args, **kw)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/mimerender.py", line 227, in wrapper
    result = target(*args, **kwargs)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/flask_restless/views.py", line 1132, in delete
    self.session.commit()
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 150, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 776, in commit
    self.transaction.commit()
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 377, in commit
    self._prepare_impl()
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 357, in _prepare_impl
    self.session.flush()
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1919, in flush
    self._flush(objects)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2037, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2001, in _flush
    flush_context.execute()
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 372, in execute
    rec.execute(self)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 526, in execute
    uow
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 60, in save_obj
    mapper, table, update)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 518, in _emit_update_statements
    execute(statement, params)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 321, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1160, in _handle_dbapi_exception
    exc_info
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/Users/felix/.virtualenvs/whrs/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
IntegrityError: (IntegrityError) NOT NULL constraint failed: project.customer_id u'UPDATE project SET customer_id=? WHERE project.id = ?' (None, 2)
```

It seems that the first id is not recognized!

**Comment by jfinkels** [comment]
I'm not sure what's going on here. We have a test case, [`test_delete_from_relation`][1], which seems to be testing this exact behavior and works just fine.

Can you provide a minimum working example that behaves this way?

[1]: https://github.com/jfinkels/flask-restless/blob/master/tests/test_views.py#L1420
