### ISSUE TITLE
No module named schema for sqlalchemy

### ISSUE THREAD

**Issue by glenwinters** [jfinkels/flask-restless#374]
I'm trying to get my script to work for the first time, and I'm getting this error:

	Traceback (most recent call last):
	  File "port_api.py", line 3, in <module>
		import flask.ext.restless
	  File "/usr/lib/python2.7/dist-packages/flask/exthook.py", line 81, in load_module
		reraise(exc_type, exc_value, tb.tb_next)
	  File "/usr/local/lib/python2.7/dist-packages/flask_restless/__init__.py", line 22, in <module>
		from .manager import APIManager
	  File "/usr/local/lib/python2.7/dist-packages/flask_restless/manager.py", line 18, in <module>
		from .views import API
	  File "/usr/local/lib/python2.7/dist-packages/flask_restless/views.py", line 44, in <module>
		from sqlalchemy.sql.schema import Column
	ImportError: No module named schema

I poked around and found that Column exists in sqlalchemy.schema. I checked that the versions of my libraries are the correct version.

**Comment by oko** [comment]
`sqlalchemy.sql.schema` doesn't exist in [SQLAlchemy v0.8](https://github.com/zzzeek/sqlalchemy/tree/rel_0_8/lib/sqlalchemy/sql), only in v0.9. However, `requirements.txt` still specifies `sqlalchemy>=0.8` so anyone with v0.8 already installed won't be upgraded and things will break.

**Comment by jfinkels** [comment]
This will be fixed when pull request #377 gets merged. For now, try simply modifying the line `from sqlalchemy.sql.schema import Column` to `from sqlalchemy import Column`.
