### ISSUE TITLE
400 - Bad Request / Unable to decode data

### ISSUE THREAD

**Issue by feoh** [jfinkels/flask-restless#486]
Folks. I'm in a frustrating fix with flask-restless. I created a quick little starter API to get my feet wet, and it WORKED! I was able to GET and PUT requests, but then when I tried to run it again the next day, I started seeing the following exception on the server side:
```
--------------------------------------------------------------------------------
ERROR in views [/Users/cpatti/anaconda/lib/python3.5/site-packages/flask_restless/views.py:1437]:
400: Bad Request
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/cpatti/anaconda/lib/python3.5/site-packages/flask/wrappers.py", line 140, in get_json
    rv = json.loads(data)
  File "/Users/cpatti/anaconda/lib/python3.5/site-packages/flask/json.py", line 149, in loads
    return _json.loads(s, **kwargs)
  File "/Users/cpatti/anaconda/lib/python3.5/json/__init__.py", line 332, in loads
    return cls(**kw).decode(s)
  File "/Users/cpatti/anaconda/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 5 column 1 (char 33)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cpatti/anaconda/lib/python3.5/site-packages/flask_restless/views.py", line 1435, in post
    data = request.get_json() or {}
  File "/Users/cpatti/anaconda/lib/python3.5/site-packages/flask/wrappers.py", line 145, in get_json
    rv = self.on_json_loading_failed(e)
  File "/Users/cpatti/anaconda/lib/python3.5/site-packages/flask/wrappers.py", line 162, in on_json_loading_failed
    raise BadRequest()
werkzeug.exceptions.BadRequest: 400: Bad Request
127.0.0.1 - - [11/Feb/2016 21:47:54] "POST /api/tracked_item HTTP/1.1" 400 -
```

Here is the client request POST:
```
POST http://0.0.0.0:8907/api/tracked_item
Content-Type: application/json
Accept: application/json
{
"description": "confidence"
}
```

And the response I get on the client is:
```
{
  "message": "Unable to decode data"
}
// POST http://0.0.0.0:8907/api/tracked_item
// HTTP/1.0 400 BAD REQUEST
// Content-Type: application/json
// Content-Length: 40
// Vary: Accept
// Content-Type: application/json
// Server: Werkzeug/0.11.2 Python/3.5.1
// Date: Fri, 12 Feb 2016 02:58:27 GMT
// Request duration: 0.110875s
```

My code is at https://github.com/feoh/clickerws/blob/master/clicker-ws.py

I sincerely appreciate any clues!

**Comment by feoh** [comment]
OK I think *maybe* the issue was no blank line between the headers and the JSON. I added said blank line and life is good.
