### ISSUE TITLE
Unclear error message when giving resource ID as integer instead of string

### ISSUE THREAD

**Issue by eualin** [jfinkels/flask-restless#534]
I am getting the following response error while trying to update a table with PATCH:

```
{u'errors': [{u'status': 409, u'code': None, u'links': None, u'title': None, u'detail': u'ID must be 1, not 1', u'source': None, u'meta': None, u'id': None}], u'meta': {}, u'jsonapi': {u'version': u'1.0'}}
```

Here is the SQLAlchemy class:

```
class Stat(postgres.Model):

    __tablename__ = 'stats'

    def __init__(self,
        res,
        met,
        cou
    ):
        self.res = res
        self.met = met
        self.cou = cou

    id = postgres.Column(postgres.Integer , primary_key=True , autoincrement=True)
    res = postgres.Column(postgres.Enum('h' , 'd' , name='stat_res_enum') , nullable=False , unique=False)
    met = postgres.Column(postgres.Enum('u_s' , 'o_t' , name='sta_met_enum') , nullable=False , unique=False)
    cou = postgres.Column(postgres.BigInteger , nullable=False , unique=False)
```

Initially, the table is empty:

```
response = requests.get(url="http://127.0.0.1/api/stats",headers={'Accept': 'application/vnd.api+json'})
response.json()
```

The response is:

```
{u'meta': {u'total': 0}, u'data': [], u'jsonapi': {u'version': u'1.0'}, u'links': {u'prev': u'http://127.0.0.1/api/stats?page[number]=0&page[size]=10', u'self': u'/api/stats', u'next': u'http://127.0.0.1/api/stats?page[number]=2&page[size]=10', u'last': u'http://127.0.0.1/api/stats?page[number]=0&page[size]=10', u'first': u'http://127.0.0.1/api/stats?page[number]=1&page[size]=10'}}
```

First, let's insert some data:

```
data = {
    'data':{
        'type':'stats',
        'attributes':{
            "res":u"h",
            "met":u"u_s",
            "cou":1
        }
    }
}
response = requests.post(url="http://127.0.0.1/api/stats",data=json.dumps(data),headers={'Content-Type': 'application/vnd.api+json', 'Accept': 'application/vnd.api+json'})
response.json()
```

The response is:

```
{u'data': {u'attributes': {u'met': u'u_s', u'cou': 1, u'res': u'h'}, u'type': u'stats', u'id': u'1', u'links': {u'self': u'http://127.0.0.1/api/stats/1'}}, u'jsonapi': {u'version': u'1.0'}}
```

Then, let's update them:

```
data = {
    'data':{
        "type":'stats',
        "id":1,
        'attributes':{
            "cou":3
        }
    }
}
response = requests.patch(url="http://127.0.0.1/api/stats/1",data=json.dumps(data),headers={'Accept' : 'application/vnd.api+json' , 'Content-Type' : 'application/vnd.api+json'})
response.json()
```

The response is:

```
{u'errors': [{u'status': 409, u'code': None, u'links': None, u'title': None, u'detail': u'ID must be 1, not 1', u'source': None, u'meta': None, u'id': None}], u'meta': {}, u'jsonapi': {u'version': u'1.0'}}
```

I have also tried to cast the value of "id" variable to String:

```
data = {
    'data':{
        "type":'stats',
        "id":"1",
        'attributes':{
            "cou":3
        }
    }
}
response = requests.patch(url="http://127.0.0.1/api/stats/1",data=json.dumps(data),headers={'Accept' : 'application/vnd.api+json' , 'Content-Type' : 'application/vnd.api+json'})
response.json()
```

But then I got the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/eualin/.bin/anaconda2/lib/python2.7/site-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/eualin/.bin/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/home/eualin/.bin/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/eualin/.bin/anaconda2/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Is this a bug or what?

**Comment by jfinkels** [comment]
@eualin Thanks for reporting this issue. First, some suggestions for next time: please submit a minimal working example. That means two things specifically:

1. *minimal* means eliminate all unnecessary code from your model and just include the problematic column (the ID in this case),
2. *working* means provide all code needed to reproduce the problem (including the code you used to create the API [`manager.create_api(...)`], in this case), preferably in a single small code snippet.

As for your issue, your first PATCH request demonstrates a usability bug: the error message should be something like "ID must be a JSON string, not a JSON integer". This must be fixed.

Your second PATCH request is not a bug in Flask-Restless, it is a bug in your code. As described in the documentation for [updating resources][1], the response for a successful PATCH request is *204 No Content*, so trying to parse a JSON object from an empty string causes an error when you try to invoke `response.json()`.

[1]: http://flask-restless.readthedocs.io/en/latest/updating.html

**Comment by eualin** [comment]
You are absolutely right. Thank you so much!

**Comment by jfinkels** [comment]
This issue should remain open until the error message is fixed.

**Comment by jfinkels** [comment]
Pull request #592 fixes the error message.
