### ISSUE TITLE
Composite association proxies still do not work

### ISSUE THREAD

**Issue by Natureshadow** [jfinkels/flask-restless#641]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/views/base.py", line 394, in new_func
    return func(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/views/base.py", line 343, in new_func
    return func(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/views/base.py", line 247, in new_func
    return func(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/views/base.py", line 447, in wrapped
    return func(*args, **kw)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/views/resources.py", line 400, in get
    return self._get_resource(resource_id)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/views/resources.py", line 335, in _get_resource
    return self._get_resource_helper(resource)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/views/base.py", line 1549, in _get_resource_helper
    result = serializer.serialize(resource, only=only)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/serialization/serializers.py", line 493, in serialize
    resource = self._dump(instance, only=only)
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/serialization/serializers.py", line 315, in _dump
    assoc_scalars = list(assoc_proxy_scalar_collections(model))
  File "/usr/local/lib/python3.5/dist-packages/flask_restless/helpers.py", line 87, in assoc_proxy_scalar_collections
    and not isinstance(v.remote_attr.property, RelationshipProperty) \
AttributeError: 'AssociationProxy' object has no attribute 'property'
```

**Comment by Natureshadow** [comment]
Any news/ideas abot this, @jfinkels?

**Comment by jfinkels** [comment]
Hi @Natureshadow, a minimal working example that demonstrates this error would be helpful for me to diagnose the problem.

**Comment by Natureshadow** [comment]
I cannot provide one. Flask-Restless throws a ton of different errors every time we change just a tiny little bit of the code.
