### ISSUE TITLE
Pretty much every test fails on master

### ISSUE THREAD

**Issue by kevinburkefreenome** [jfinkels/flask-restless#688]
Hi, 
Per the instructions in the README, I checked out the project and tried to run the tests, and am getting 520 failures out of 544 tests total. Most of the failures look like this:

```
Traceback (most recent call last):
  File "/Users/kevin/src/github.com/jfinkels/flask-restless/tests/test_serialization.py", line 502, in test_multiple_exceptions_on_included
    self.manager.create_api(self.Article)
  File "/Users/kevin/src/github.com/jfinkels/flask-restless/flask_restless/manager.py", line 891, in create_api
    blueprint = self.create_api_blueprint(blueprint_name, *args, **kw)
  File "/Users/kevin/src/github.com/jfinkels/flask-restless/flask_restless/manager.py", line 774, in create_api_blueprint
    view_func=relationship_api_view)
  File "/Users/kevin/.pyenv/versions/3.6.6/lib/python3.6/site-packages/flask/blueprints.py", line 206, in add_url_rule
    assert '.' not in view_func.__name__, "Blueprint view function name should not contain dots"
AssertionError: Blueprint view function name should not contain dots
```

I am running CPython 3.6.6, installed via Pyenv, on a Mac. I ran `pip install -r requirements/test-cpython.txt`. I also needed to run `pip install psycopg2-binary` to get the tests to even start running.

Searching the issue history led to issue https://github.com/jfinkels/flask-restless/issues/686. Perhaps these are related? I am confused though about how the tests are passing in Travis CI if they are not passing here.

**Comment by kevinburkefreenome** [comment]
Oh, scratch that, it looks like the tests are also failing on Travis CI.
